name: Generate Subscription Links

on:
  schedule:
    - cron: '0 0 * * *' # 每天 UTC 00:00 运行 (北京时间 08:00)
  workflow_dispatch: # 允许手动触发

jobs:
  generate_links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get IP addresses
        id: get_ips
        run: |
          IP_LIST=$(curl -s https://raw.githubusercontent.com/ymyuuu/IPDB/main/proxy.txt | grep -E '^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')
          echo "::set-output name=ips::$IP_LIST"

      - name: Generate subscription links
        run: |
          IPS="${{ steps.get_ips.outputs.ips }}"
          echo "" > sub.txt
          while IFS= read -r -d $'\n' IP; do
            # 去除 IP 地址末尾的任何额外空格或回车符
            IP=$(echo "$IP" | xargs)
            if [[ -n "$IP" ]]; then # 确保 IP 不为空
              LINK="vless://feefeb96-bfcf-4a9b-aac0-6aac771c1b98@${IP}:443?encryption=none&security=tls&sni=pages.seaw.us.kg&fp=random&type=ws&host=pages.seaw.us.kg#US_6"
              echo "$LINK" >> sub.txt
            fi
          done <<< "$IPS"


      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add sub.txt
          git commit -m "Update subscription links" || echo "No changes to commit"
          git push origin main
